import { formatCadAmount, pricing } from "./pricing.js"

const progressionInstallmentPrice = {
  fr: formatCadAmount(pricing.offers.progression_block.installmentPriceCad, "fr"),
  en: formatCadAmount(pricing.offers.progression_block.installmentPriceCad, "en"),
}
const portalCopyByLocale = {
  fr: {
    seoTitle: "Connexion au portail client | Méthode Secondaire",
    seoDescription:
      "Connexion réservée aux parents et aux tuteurs déjà accompagnés pour suivre les séances, paiements, notes et prochaines actions.",
    badge: "Espace client Méthode Secondaire",
    title: "Accédez à votre espace client.",
    subtitle:
      "Cet espace est réservé aux parents et aux tuteurs déjà accompagnés. Connectez-vous avec le code reçu par courriel pour consulter vos séances, paiements et suivis.",
    firstSessionRequestBadge: "Demande de première séance",
    firstSessionRequestTitle: "Parlez-nous de la situation de votre jeune.",
    firstSessionRequestSubtitle:
      "Décrivez le niveau, la matière et le besoin. L'équipe vous proposera ensuite un tuteur et un créneau; le portail servira au suivi après votre première confirmation.",
    newClientPrompt: "Vous cherchez un tuteur pour la première fois ?",
    newClientAction: "Demander une première séance",
    parent: "Parent",
    tutor: "Tuteur",
    operator: "Équipe",
    loginTab: "Connexion",
    createTab: "Ma demande",
    existingAccessTitle: "J'ai déjà un accès",
    createParentTitle: "Demande de première séance",
    createTutorTitle: "Demande d'accès tuteur",
    email: "Adresse email",
    code: "Code reçu par email",
    sendCode: "Recevoir un code",
    verifyCode: "Se connecter",
    parentName: "Nom du parent",
    phone: "Téléphone",
    studentLevelSubject: "Niveau et matière",
    mainConcern: "Besoin principal",
    preferredFormat: "Format souhaité",
    tutorName: "Nom du tuteur",
    tutorSubjects: "Matières et niveaux",
    createParentAccount: "Envoyer ma demande",
    createTutorRequest: "Demander l'accès",
    privacyConsent: "J'accepte que Méthode Secondaire conserve ces renseignements pour organiser les séances, le suivi et les paiements.",
    codeSent:
      "Si un accès existe pour cette adresse, un code vient d'être envoyé. Vérifiez aussi vos indésirables.",
    sendingCode: "Envoi du code...",
    signingIn: "Connexion...",
    creatingAccount: "Création du compte...",
    loadingDashboard: "Chargement de votre espace...",
    loadingDashboardSlow: "Connexion au CRM en cours. Vos données restent sécurisées.",
    serviceTimeout:
      "Le service prend plus de temps que prévu. Rafraîchissez dans un instant; votre session et vos données sont conservées.",
    dashboardDisplayError:
      "Le tableau a reçu les données, mais une section n'a pas pu s'afficher. Vos données restent intactes.",
    retryDashboard: "Réessayer le tableau",
    accountCreated:
      "Demande reçue. Un code vient d'être envoyé à votre email pour confirmer l'accès à votre suivi.",
    existingAccountCodeSent:
      "Un accès existe déjà pour cette adresse. Un code vient d'être envoyé.",
    tutorRequestSent:
      "Demande reçue. L'accès tuteur sera activé après validation dans le roster.",
    tutorInviteRequired: "L'accès tuteur est créé et envoyé uniquement par l'équipe Méthode Secondaire.",
    tutorInviteTitle: "Accès tuteurs",
    tutorCreateTitle: "Ajouter un tuteur",
    tutorCreateIntro: "Créez sa fiche, puis le tuteur reçoit son code de connexion par email.",
    tutorExistingTitle: "Accès déjà créés",
    tutorInviteStatus: "Statut d'accès",
    inviteTutor: "Créer et envoyer l'accès",
    tutorInvited: "Accès tuteur créé. Un code de connexion a été envoyé.",
    createTutor: "Créer le tuteur et envoyer l'accès",
    tutorCreatedAndInvited: "Tuteur créé et accès envoyé par email.",
    tutorCreatedInvitePending: "Tuteur créé. Renvoyez son accès ci-dessous lorsque l'envoi email est disponible.",
    tutorDetailsRequired: "Ajoutez le nom, l'email, les matières, les niveaux, le format et une capacité de 1 à 40 élèves.",
    tutorEmailInUse: "Cette adresse email appartient déjà à un tuteur.",
    tutorLevels: "Niveaux couverts",
    tutorWeeklyCapacity: "Capacité hebdomadaire (élèves)",
    tutorLanguage: "Langue de travail",
    tutorZones: "Zone ou secteur",
    tutorRate: "Tarif horaire (CAD/h — base 28 $, ajustable selon l’expérience et le rôle)",
    tutorRateInvalid: "Le tarif horaire doit être d’au moins 28 $ CAD/h.",
    tutorNotes: "Note interne (facultative)",
    tutorInviteDetailsRequired: "Choisissez un tuteur actif avec une adresse email calendrier.",
    logout: "Déconnexion",
    cancel: "Annuler",
    refresh: "Rafraîchir",
    setupPending:
      "Le portail est prêt côté site, mais l'envoi de code doit être autorisé dans Apps Script si le courriel ne part pas.",
    apiUnavailable:
      "L'API du portail ne répond pas ici. En local, relancez le site puis réessayez; en production, vérifiez la configuration Vercel.",
    accountRequired: "Ajoutez au minimum le nom et l'email pour créer l'accès.",
    privacyConsentRequired: "Le consentement est requis pour créer le compte parent.",
    emailRequired: "Entrez une adresse email valide.",
    emailNotAuthorized:
      "L'envoi des codes email doit être autorisé une fois dans Google Apps Script. Réessayez dans quelques instants ou contactez Méthode Secondaire.",
    emailQuotaReached:
      "L'envoi de codes est temporairement indisponible. Réessayez plus tard ou contactez Méthode Secondaire.",
    emailSendFailed:
      "Le code n'a pas pu être envoyé. Réessayez dans quelques instants ou contactez Méthode Secondaire.",
    loginFailed: "Le code ou l'adresse email est incorrect. Demandez un nouveau code et réessayez.",
    loginCooldown: "Trop de codes incorrects ont été saisis. Attendez 15 minutes avant de demander un nouveau code.",
    codeExpired: "Ce code a expiré. Demandez un nouveau code.",
    sessionExpired: "Votre session n'est plus active. Demandez un nouveau code pour vous reconnecter.",
    parentDashboard: "Espace parent",
    tutorDashboard: "Espace tuteur",
    operatorDashboard: "Gestion des séances",
    parentJourneyTitle: "Votre parcours",
    parentJourneyProfile: "Profil reçu",
    parentJourneyMatching: "Tuteur proposé",
    parentJourneyBooking: "Séance réservée",
    parentJourneyFollowUp: "Suivi en cours",
    parentJourneyCurrent: "En cours",
    parentJourneyDone: "Terminé",
    parentJourneyEyebrow: "Le suivi de votre famille",
    parentJourneyNext: "Prochaine étape",
    parentJourneyCount: "étapes complétées",
    parentJourneyCompleteMessage: "Tout est en place. Vous gardez maintenant le fil dans le portail.",
    parentActionEyebrow: "À faire maintenant",
    parentActionProfile: "Compléter votre profil",
    parentActionProfileText: "Ajoutez les quelques détails utiles pour que le jumelage parte du bon contexte.",
    parentActionMatching: "Le jumelage est en préparation",
    parentActionMatchingText: "Votre demande est bien reçue. Nous vous proposons le bon tuteur avant la réservation.",
    parentActionBooking: "Choisir une première séance",
    parentActionBookingText: "Votre tuteur est prêt : choisissez simplement le créneau qui convient à votre famille.",
    parentActionPayment: "Finaliser le paiement",
    parentActionPaymentText: "Un paiement attend votre attention pour garder la séance confirmée.",
    parentActionMessage: "Répondre au dernier message",
    parentActionMessageText: "Une réponse rapide aide l'équipe et le tuteur à bien préparer la suite.",
    parentActionAllSet: "Tout est à jour",
    parentActionAllSetText: "Votre famille est prête. Les prochains repères apparaîtront ici au bon moment.",
    parentActionOpen: "Voir la prochaine étape",
    parentNavLabel: "Navigation de l’espace parent",
    parentNavToday: "Aujourd’hui",
    parentNavSessions: "Séances",
    parentNavMessages: "Messages",
    parentNavAccount: "Famille et compte",
    sessionProgressEyebrow: "Repères de la séance",
    sessionProgressTitle: "Le fil de la prochaine séance",
    sessionProgressPrepare: "Préparer la séance",
    sessionProgressMeet: "Séance avec le tuteur",
    sessionProgressRecap: "Lire le bilan",
    sessionProgressUpcoming: "À venir",
    rhythmEyebrow: "Votre rythme",
    rhythmTitle: "Un suivi qui reste simple",
    rhythmNoContract: "Aucun abonnement ni renouvellement automatique",
    rhythmNoContractText: "La cadence est choisie avec vous après le jumelage. Elle organise les séances du bloc sans créer un abonnement.",
    rhythmSameTutor: "Même tuteur, même créneau",
    rhythmSameTutorText: "Le suivi garde son contexte : moins de répétitions, plus de continuité.",
    rhythmDeadline: "Échéance de planification",
    rhythmDeadlineFallback: `Prévoyez toute modification au moins ${pricing.cancellation.noticeHours} h avant une séance.`,
    rhythmDeadlinePassed: `La fenêtre de ${pricing.cancellation.noticeHours} h est passée : l'équipe peut encore étudier un ajustement.`,
    rhythmPause: "Mettre le rythme sur pause",
    rhythmResume: "Reprendre le rythme",
    rhythmPauseHelp: `Une pause s'applique aux prochaines séances qui ne sont pas encore dans la fenêtre de ${pricing.cancellation.noticeHours} h. Aucun paiement réel n'est lancé depuis cette carte.`,
    rhythmPauseConfirmed: "Le rythme est mis sur pause. Les séances déjà confirmées restent à vérifier séparément.",
    rhythmResumeConfirmed: "Le rythme est repris. L'équipe et le tuteur voient de nouveau votre cadence.",
    rhythmPauseSetup: "L'équipe active d'abord ce rythme dans votre dossier; vous pourrez ensuite le mettre sur pause ici.",
    rhythmManage: "Gérer les séances",
    rhythmPriceNote: "La cadence est confirmée après le jumelage; elle ne renouvelle jamais le bloc automatiquement.",
    programEyebrow: "Votre bloc",
    programCredits: "séances restantes",
    programOutOf: "sur",
    programUsed: "séances utilisées",
    programAction: "Voir les séances du programme",
    programPending: "Programme à activer",
    programMidpointPaymentIntro: "Crédits restants : {credits}. Réglez le deuxième versement de {amount} avant de réserver une sixième séance.",
    programMidpointPaymentAction: "Préparer le deuxième paiement",
    programMidpointPaymentOpen: "Ouvrir le paiement Stripe sécurisé",
    programMidpointPaymentUnavailable: "Le paiement a été préparé, mais son lien Stripe sécurisé n’est pas encore disponible. Réessayez dans quelques instants.",
    materialsEyebrow: "Avant la séance",
    materialsTitle: "Préparer la séance",
    materialsDescription: "Une photo du devoir, du chapitre ou de l'examen aide le tuteur à cibler plus vite.",
    materialsNoSession: "Dès qu'une séance est prévue, vous pourrez préparer ce que votre jeune veut travailler ici.",
    materialsCapture: "Prendre une photo",
    materialsAddFile: "Ajouter des photos ou un PDF",
    materialsSelected: "Sur cet appareil",
    materialsReceived: "Documents reçus",
    materialsRemove: "Retirer",
    materialsNote: "Ce qui bloque le plus (facultatif)",
    materialsNotePlaceholder: "Ex. Je ne comprends pas comment commencer la question 4.",
    materialsFileTypes: "Photos JPG, PNG ou WebP et PDF seulement.",
    materialsFileLimit: "Maximum 2,5 Mio par fichier.",
    materialsSessionLimit: "Maximum cinq fichiers par séance.",
    materialsFileInvalid: "Ce fichier ne peut pas être traité. Choisissez une photo ou un PDF valide.",
    materialsProcessingFailed: "La photo n'a pas pu être préparée. Réessayez ou choisissez un autre fichier.",
    materialsNotAvailable: "Les documents peuvent être partagés ou retirés seulement avant une séance à venir.",
    materialsStorageNotConfigured: "Le transfert sécurisé des documents n'est pas encore configuré. Contactez Méthode Secondaire.",
    materialsStorageFailed: "Le document n'a pas pu être enregistré. Réessayez dans quelques instants.",
    materialsCleanupFailed: "Le document n'a pas pu être partagé et son nettoyage doit être vérifié par l'équipe.",
    materialsShareFailed: "L'accès du tuteur au document n'a pas pu être confirmé. Le document n'a pas été partagé.",
    materialsWithdrawFailed: "Le document n'a pas pu être retiré. Réessayez ou contactez Méthode Secondaire.",
    materialsReadyState: "Prêt",
    materialsUploading: "Envoi...",
    materialsShared: "Partagé avec votre tuteur",
    materialsFailed: "Échec",
    materialsRetry: "Réessayer",
    materialsSendToTutor: "Envoyer au tuteur",
    materialsWithdraw: "Retirer",
    materialsWithdrawn: "Le document a été retiré de l'accès du tuteur.",
    materialsRetention: "Les documents partagés sont supprimés 30 jours après la fin de la séance.",
    materialsOpen: "Ouvrir le document",
    materialsOpenUnavailable: "Document temporairement indisponible",
    tutorMaterialsEyebrow: "Avant la séance",
    tutorMaterialsTitle: "Documents partagés par les parents",
    calendarNoSessions: "Aucune séance prévue cette semaine.",
    profileTitle: "Profil de suivi",
    profileIntro: "Gardez les renseignements de l'élève à jour pour que chaque séance parte du bon contexte.",
    profileSaved: "Profil de suivi mis à jour.",
    profileDetailsRequired: "Ajoutez au minimum votre nom pour enregistrer le profil.",
    profileTimeline: "Rythme ou échéance importante",
    profileSave: "Enregistrer le profil",
    welcome: "Bonjour",
    nextSession: "Prochaine séance",
    manageSession: "Gérer cette séance",
    noNextSession: "Aucune séance confirmée à venir.",
    sessions: "Séances",
    upcomingSessions: "À venir",
    followUpSessions: "À régulariser",
    pastSessions: "Passées",
    cancelledSessions: "Annulées",
    scheduleSession: "Planifier une séance",
    chooseParent: "Choisir un parent",
    chooseTutor: "Choisir un tuteur",
    sessionDate: "Date et heure",
    duration: "Durée",
    studentName: "Nom de l'élève",
    sessionType: "Type de séance",
    sessionFormat: "Format",
    location: "Lieu ou lien de rencontre",
    recurrence: "Récurrence",
    sessionPrice: "Montant à facturer (CAD)",
    sessionPriceDefault: "Tarif par défaut",
    sessionPriceHelp: "Entrez 0 $ pour une séance gratuite. À partir de 1 $, un Checkout Stripe Test est créé après confirmation.",
    createSession: "Envoyer la proposition",
    sessionCreated: "Séance proposée aux deux personnes pour confirmation.",
    confirmSession: "Confirmer",
    requestChange: "Demander un ajustement",
    rescheduleSession: "Modifier le créneau",
    rescheduleTitle: "Proposer un nouveau créneau",
    rescheduleDate: "Nouvelle date et heure",
    rescheduleDuration: "Nouvelle durée (minutes)",
    rescheduleSave: "Envoyer la nouvelle proposition",
    sessionRescheduled: "Nouveau créneau proposé. Le parent et le tuteur doivent maintenant confirmer.",
    rescheduleNotAvailable: "Cette séance ne peut plus être replanifiée.",
    cancelSession: "Annuler la séance",
    cancellationPolicy: `Avec ${pricing.cancellation.noticeHours} h de préavis, le report est garanti. Sous ce délai, l'équipe examine la demande; aucun crédit ou paiement n'est retiré automatiquement.`,
    cancellationConfirmed: "Séance annulée. Le calendrier et le paiement non réglé ont été mis à jour.",
    cancellationReview: "Demande d'annulation transmise à l'équipe pour révision.",
    operatorCancellationConfirm: "Annuler cette séance? Le parent, le tuteur, le calendrier et le paiement non réglé seront mis à jour.",
    operatorCancellationConfirmed: "Séance annulée par l'équipe. Le calendrier et le paiement ont été mis à jour.",
    cancellationNotAvailable: "Cette séance ne peut plus être annulée depuis le portail.",
    sessionConfirmed: "Confirmation enregistrée. Le calendrier et le paiement suivront dès que les deux personnes ont confirmé.",
    sessionChangeRequested: "Demande d'ajustement envoyée à l'équipe.",
    confirmationWaiting: "En attente de l'autre confirmation",
    parentConfirmed: "Parent confirmé",
    tutorConfirmed: "Tuteur confirmé",
    paymentReady: "Paiement prêt",
    sessionAwaitingTutor: "Vous avez confirmé — en attente de la confirmation du tuteur.",
    sessionAwaitingParent: "Le tuteur a confirmé — votre confirmation est attendue.",
    sessionProposalExpired: "Cette proposition est expirée.",
    sessionProposalExpiredText: "Demandez un ajustement et l'équipe vous proposera un nouveau créneau.",
    sessionRecapTitle: "Bilan de la séance",
    planSetupTitle: "Blocs et paiements",
    planSetupIntro: "Créez un Bloc d'élan ou un Bloc de progression. La vérification Stripe accorde automatiquement les crédits prévus, une seule fois.",
    planChoose: "Formule",
    planChooseParent: "Parent",
    planChooseStudent: "Élève",
    planChooseTutor: "Tuteur",
    planCadence: "Cadence après le jumelage",
    planCadenceHelp: "Choisissez un rythme seulement après avoir confirmé le tuteur et les disponibilités de la famille.",
    planCadenceOptions: {
      one_time: "À planifier au besoin",
      weekly: "Chaque semaine",
      biweekly: "Aux deux semaines",
    },
    planWeekday: "Jour habituel",
    planTime: "Heure habituelle",
    planSessionLink: "Suivi lié (facultatif)",
    planSessionLinkNone: "Aucune formule liée",
    planSessionLinkHelp: "Liez cette séance au suivi actif. Un crédit est réservé automatiquement pour le bloc de 10 séances.",
    planDetailsRequired: "Confirmez le jumelage élève-tuteur, puis une cadence, un jour et une heure réalistes avant de créer le bloc.",
    planActivate: "Créer le bloc et envoyer le paiement",
    planEnrollmentSaved: "Bloc créé dans le dossier parent.",
    planPaymentRequestCreated: "Demande de paiement créée. La vérification Stripe activera automatiquement les crédits, une seule fois.",
    planPaymentRequestTitle: "Demande de paiement du bloc",
    planPaymentRequestOpen: "Ouvrir le paiement Stripe",
    planMidpointTitle: "Paiement de mi-parcours du Bloc de progression",
    planMidpointIntro: `Le deuxième paiement de ${progressionInstallmentPrice.fr} devient disponible lorsque les cinq premiers crédits sont tous réservés ou utilisés.`,
    planMidpointAction: "Créer le paiement de mi-parcours",
    planMidpointNone: "Aucun Bloc de progression n'a encore atteint le point de mi-parcours.",
    planPaymentStageNotReady: "Les cinq premiers crédits doivent être entièrement réservés ou utilisés avant ce paiement.",
    planPaymentRequestBusy: "La demande de paiement est en cours de création. Réessayez dans quelques secondes.",
    planAlreadyActive: "Cette famille a déjà cette formule active pour cet élève. Ouvrez-la plutôt que de créer un second programme.",
    planEnrollmentBusy: "La formule est en cours d’activation. Réessayez dans quelques secondes.",
    planCannotAdjust: "Cette formule n’est plus active : ses crédits ne peuvent plus être modifiés.",
    planEnrollmentPending: "Formule créée en attente : confirmez le paiement avant d'ajouter les crédits.",
    planNoPlans: "Les formules seront disponibles après la synchronisation CRM.",
    planAdjustTitle: "Correction manuelle exceptionnelle de crédits",
    planAdjustHelp: "Réservé aux corrections exceptionnelles. Une raison précise est obligatoire; les paiements normaux sont crédités automatiquement par Stripe.",
    planSelectEnrollment: "Programme parent",
    planCreditAmount: "Crédits à ajouter ou retirer",
    planCreditReason: "Raison de l'ajustement",
    planCreditReasonRequired: "Ajoutez une raison avant d'enregistrer cette correction exceptionnelle.",
    planCreditSaved: "Crédits mis à jour.",
    paymentDemoAction: "Payer en simulation",
    paymentDemoSuccess: "Paiement simulé confirmé. Aucune carte n'a été débitée.",
    paymentDemoNotAvailable: "Cette séance utilise déjà le paiement par carte ou ne peut plus être simulée.",
    bookingTitle: "Réserver une séance",
    bookingIntro: "Choisissez un créneau. Un lien de paiement Stripe sécurisé sera créé pour votre réservation.",
    bookingTutorAndSubjects: "Tuteur et matières",
    bookingTutorAssignmentRequired: "Choisissez d’abord le tuteur qui accompagnera cette séance.",
    bookingTutorAssignmentSummary: "Tuteur choisi : {tutor} — Matières assignées : {subjects}",
    bookingPaymentNotice: "Le paiement par carte s’ouvre uniquement dans la page Stripe sécurisée.",
    bookingCreditIntro: "Choisissez un créneau : un crédit du programme sera réservé pour cette séance.",
    bookingNoSlots: "Aucun créneau n'est ouvert pour l'instant.",
    bookingPrice: "Prix de cette séance",
    bookingProgramCredit: "1 crédit du programme",
    bookingPlanCredit: "1 crédit du programme sera réservé pour cette séance.",
    bookingProgramCreditNotice: "Le crédit est réservé maintenant, puis consommé seulement après la séance.",
    bookingProgramPaymentRequired: "Les cinq premiers crédits sont déjà réservés ou utilisés. Accédez au paiement du bloc dans « Famille et compte » avant de réserver une autre séance.",
    bookingProgramPaymentAction: "Accéder au paiement du bloc",
    matchingPendingTitle: "Nous préparons le bon jumelage",
    matchingPendingIntro: "Votre profil est reçu. L'équipe vous propose un tuteur avant de vous afficher ses créneaux.",
    matchingPendingCall: "Situation urgente ou besoin complexe? Appelez-nous.",
    chooseSlot: "Choisir ce créneau",
    bookingStudentName: "Nom de l'élève",
    bookingChooseChild: "Élève concerné",
    bookingAddChild: "Ajoutez d'abord un élève pour réserver un créneau.",
    bookSession: "Réserver et payer",
    bookWithProgramCredit: "Réserver avec un crédit",
    bookingLoading: "Validation du créneau...",
    bookingCheckoutReady: "Séance réservée. Votre paiement Stripe sécurisé est prêt.",
    bookingTestCheckoutReady: "Séance réservée. Votre Checkout Stripe de test est prêt; aucune carte réelle ne sera débitée.",
    bookingPaymentSetupRequired: "Séance réservée, mais le Checkout Stripe n’est pas encore configuré. Aucun paiement n’a été effectué; l’équipe doit finaliser la configuration.",
    bookingCreditSuccess: "Séance réservée. Un crédit du programme est maintenant réservé.",
    bookingFreeSuccess: "Séance réservée. Elle est gratuite : aucun paiement n’est requis.",
    bookingDetailsRequired: "Choisissez un créneau et ajoutez le nom de l'élève.",
    childrenTitle: "Mes élèves",
    childrenIntro: "Chaque enfant garde son niveau, son tuteur et son suivi. Ajoutez tous les enfants de la famille ici.",
    childName: "Nom de l'élève",
    childLevelSubject: "Niveau et matières",
    childLearningNotes: "Contexte utile pour le tuteur",
    childTutor: "Tuteur de l'élève",
    childTutorAssignments: "Tuteurs et matières assignées",
    childTutorAssignmentSubjects: "Matières attribuées",
    childTutorAssignmentAdd: "Ajouter cette attribution",
    childTutorAssignmentSave: "Enregistrer l’attribution",
    childTutorAssignmentDeactivate: "Retirer cette attribution",
    childTutorAssignmentSaved: "Attribution tuteur et matières enregistrée.",
    childTutorAssignmentDeactivated: "Attribution retirée.",
    chooseStudent: "Choisir un élève",
    addChild: "Ajouter un élève",
    saveChild: "Enregistrer l'élève",
    childSaved: "Fiche élève enregistrée.",
    childDetailsRequired: "Ajoutez au minimum le nom de l'élève.",
    childNotFound: "Cette fiche élève n'est plus disponible.",
    childTutorAssigned: "Tuteur assigné à cet élève.",
    childTutorAssignmentRequired: "Choisissez un élève et un tuteur actif.",
    studentTutorAssignmentDetailsRequired: "Choisissez un tuteur actif et indiquez au moins une matière.",
    studentTutorAssignmentRequired: "Choisissez le tuteur et les matières avant de sélectionner un créneau.",
    studentTutorAssignmentNotAvailable: "Cette attribution n’est plus disponible. Actualisez le portail et choisissez de nouveau.",
    studentTutorAssignmentExists: "Ce tuteur est déjà attribué à cet élève. Modifiez ses matières dans l’attribution existante.",
    noChildren: "Aucun élève n'est encore ajouté.",
    calendarTitle: "Calendrier",
    calendarIntro: "Séances, confirmations et rappels restent visibles au même endroit.",
    calendarToday: "Aujourd'hui",
    calendarInviteSent: "Invitation calendrier envoyée",
    calendarReminderSent: "Rappel envoyé",
    calendarNotSynced: "Synchronisation en attente",
    activityTitle: "Historique de la famille",
    activityIntro: "Séances, résumés, messages, paiements et demandes dans l'ordre.",
    noActivity: "Les prochaines actions et les échanges apparaîtront ici.",
    todayTitle: "Aujourd'hui",
    todayIntro: "Les appels, confirmations, rappels et séances qui demandent une action maintenant.",
    todayCalls: "Appels à faire",
    todayConfirmations: "Séances à confirmer",
    todaySessions: "Séances du jour",
    todayReminders: "Rappels à envoyer",
    bookingSlotUnavailable: "Ce créneau vient d'être pris. Choisissez-en un autre.",
    parentUpdateSent: "Le résumé parent a été envoyé.",
    nextSessionProposed: "La prochaine séance a été proposée automatiquement.",
    sessionDetailsRequired: "Choisissez un parent, un tuteur et une date future.",
    sessionParticipantMissing: "Le parent ou le tuteur choisi n'est plus disponible.",
    sessionTimeConflict: "Ce tuteur a déjà une séance à ce moment. Choisissez un autre créneau.",
    parentManagement: "Gestion des parents",
    teamCreateParentTitle: "Ajouter un parent",
    createParentIntro: "Ajoutez une famille issue d'un appel ou d'une recommandation. L'accès portail reste sous votre contrôle.",
    createParentAccess: "Créer aussi l'accès portail parent",
    createParentConsent: "Le parent a consenti à l'ouverture de son dossier et de son accès portail.",
    createParent: "Créer le parent",
    parentCreated: "Parent ajouté au CRM.",
    parentCreatedWithAccess: "Parent ajouté et accès portail activé. Le parent peut maintenant demander son code par email.",
    callFollowUp: "Suivi de l'appel",
    callFollowUpIntro: "Gardez chaque rappel commercial visible, puis envoyez le parent au matching quand il est pret.",
    callParent: "Appeler le parent",
    leadStatus: "Etat du lead",
    callbackNotes: "Notes d'appel",
    saveCallFollowUp: "Enregistrer le suivi",
    callFollowUpSaved: "Suivi d'appel enregistre.",
    leadFollowUpStatusRequired: "Choisissez un etat de suivi valide.",
    parentManagementIntro: "Toutes les fiches parents sont ici. Vous pouvez les modifier, assigner un tuteur ou les supprimer avec confirmation.",
    parentIntentLabel: "Contexte initial",
    parentIntentExam: "Pr\u00e9paration d'examen",
    parentIntentHomework: "Devoirs difficiles",
    parentIntentOngoing: "Difficult\u00e9s r\u00e9currentes",
    chooseParentAccount: "Choisir un compte parent",
    assignedTutor: "Tuteur assigné",
    saveParent: "Enregistrer le parent",
    parentSaved: "Compte parent mis à jour.",
    parentDetailsRequired: "Ajoutez le nom et une adresse email valide.",
    parentNotFound: "Ce compte parent n'est plus disponible.",
    parentEmailInUse: "Cette adresse email appartient déjà à un autre parent.",
    parentAccess: "Accès portail",
    activateParent: "Activer l'accès",
    deactivateParent: "Désactiver l'accès",
    parentAccessUpdated: "Accès parent mis à jour.",
    assignTutor: "Assigner ce tuteur",
    tutorAssigned: "Tuteur assigné. Vous pouvez maintenant planifier la séance.",
    assignmentDetailsRequired: "Choisissez un parent et un tuteur actif.",
    deleteParent: "Supprimer le parent",
    confirmationEmail: "Retapez l'email du parent pour confirmer",
    parentDeleteConfirmationRequired: "L'email de confirmation ne correspond pas.",
    parentDeleted: "Compte parent et données associées supprimés.",
    tutorManagement: "Gestion des tuteurs",
    tutorManagementIntro: "Tous les tuteurs, actifs ou non, sont réunis ici. La suppression retire aussi leurs accès, disponibilités et séances liées.",
    tutorDetails: "Détails du tuteur",
    tutorStatus: "Statut du roster",
    tutorCapacity: "Capacité",
    deleteTutor: "Supprimer le tuteur",
    confirmationTutorEmail: "Retapez l'email du tuteur pour confirmer",
    tutorDeleteConfirmationRequired: "L'email de confirmation ne correspond pas.",
    tutorDeleted: "Tuteur et données associées supprimés.",
    tutorNotFound: "Ce tuteur n'est plus disponible.",
    tutorPublicProfileTitle: "Profil public du tuteur",
    tutorPublicProfileIntro: "Visible seulement après validation de l'équipe et consentement du tuteur.",
    tutorPublicProfileDisplayName: "Nom affiché",
    tutorPublicProfilePhotoUrl: "URL HTTPS de la photo (facultative)",
    tutorPublicProfilePhotoAltFr: "Texte alternatif photo (FR)",
    tutorPublicProfilePhotoAltEn: "Texte alternatif photo (EN)",
    tutorPublicProfileHeadlineFr: "Titre court (FR)",
    tutorPublicProfileHeadlineEn: "Titre court (EN)",
    tutorPublicProfileBioFr: "Présentation (FR)",
    tutorPublicProfileBioEn: "Présentation (EN)",
    tutorPublicProfileStyleFr: "Style d'accompagnement (FR)",
    tutorPublicProfileStyleEn: "Style d'accompagnement (EN)",
    tutorPublicProfileVisibility: "Visibilité",
    tutorPublicProfileDraft: "Brouillon",
    tutorPublicProfilePublished: "Publié",
    tutorPublicProfileHidden: "Masqué",
    tutorPublicProfileConsent: "Le tuteur a consenti à la publication de ce profil et de sa photo.",
    tutorPublicProfilePublicationRequired: "Pour publier, ajoutez le contenu français et anglais requis et confirmez le consentement.",
    tutorPublicProfileSave: "Enregistrer le profil public",
    tutorPublicProfileSaved: "Profil public enregistré.",
    messagesTitle: "Messages de séance",
    messageSession: "Séance concernée",
    messagePlaceholder: "Écrire un message",
    sendMessage: "Envoyer le message",
    messageSent: "Message envoyé. Le destinataire a aussi été avisé par email.",
    messageSentPortal: "Message envoyé dans le portail.",
    responseSla: "Réponse attendue dans les 24 h. L'équipe est alertée si le délai est dépassé.",
    messageRequired: "Écrivez un message avant de l'envoyer.",
    messageNotAllowed: "La messagerie est réservée au parent et au tuteur de cette séance.",
    notes: "Résumés",
    payments: "Paiements",
    amount: "Montant",
    freeSession: "Gratuit",
    pay: "Payer",
    paid: "Payé",
    paymentDueOneHour: "Paiement à effectuer dans l’heure",
    paymentDueUntil: "À régler avant",
    paymentLinkPreparing: "Votre lien Stripe sécurisé est en préparation. Actualisez dans un instant; aucun paiement n’a été débité.",
    paymentLinkExpired: "Ce lien de paiement a expiré.",
    requestNewPaymentLink: "Demander un nouveau lien de paiement",
    paymentReissueSuccess: "Un nouveau lien de paiement sécurisé est prêt pendant une heure.",
    bookingReleased: "La réservation a été libérée. Choisissez un nouveau créneau avant de payer.",
    meetPreparing: "Lien Google Meet en préparation",
    joinGoogleMeet: "Rejoindre Google Meet",
    requestTitle: "Demander un suivi",
    requestHistory: "Suivi des demandes",
    requestQueue: "Demandes à traiter",
    requestStatus: "État",
    requestSave: "Mettre à jour",
    requestUpdated: "Demande mise à jour.",
    requestStatusRequired: "Choisissez un état valide.",
    requestNotFound: "Cette demande n'est plus disponible.",
    parentNoteTitle: "Ajouter une note",
    parentNoteSession: "Séance concernée",
    parentNoteMessage: "Information à partager avec l'équipe ou le tuteur",
    parentNoteSent: "Note ajoutée au suivi de la séance.",
    sessionPrepTitle: "Préparer la prochaine séance",
    sessionPrepIntro: "Partagez la priorité, un devoir ou un changement de contexte directement avec le tuteur.",
    sessionPrepMessage: "Priorité, devoir, évaluation ou contexte à connaître avant la séance",
    sessionPrepSent: "Préparation envoyée au tuteur dans l'espace de séance.",
    requestSubject: "Sujet",
    requestMessage: "Message",
    sendRequest: "Envoyer la demande",
    requestSent: "Demande envoyée. Elle apparaît dans le CRM pour traitement.",
    noteTitle: "Note après séance",
    chooseSession: "Choisir une séance",
    attendance: "Présence",
    focusWorked: "Ce qui a été travaillé",
    wins: "Ce qui avance bien",
    stuckPoints: "Ce qui bloque encore",
    homeworkNext: "Travail avant la prochaine séance",
    parentSummary: "Résumé parent",
    studentConfidence: "Confiance de l'élève",
    nextGoal: "Prochain objectif",
    riskLevel: "Risque",
    recommendation: "Recommandation",
    submitNote: "Envoyer la note",
    noteSent: "Note reçue. Le résumé parent est prêt à être validé.",
    noteNotReady: "La note peut être déposée après la fin de la séance.",
    availabilityTitle: "Mes disponibilités",
    availabilityIntro: "Les créneaux ouverts ici deviennent réservables par les parents dans le portail.",
    availabilityAdd: "Ajouter une disponibilité",
    availabilitySave: "Enregistrer la disponibilité",
    availabilityEdit: "Modifier",
    availabilityDay: "Jour",
    availabilityStart: "Début",
    availabilityEnd: "Fin",
    availabilityStatus: "Statut",
    availabilitySaved: "Disponibilité mise à jour.",
    availabilityPause: "Mettre en pause",
    availabilityOpen: "Ouvrir",
    availabilityEmpty: "Aucune disponibilité n'est publiée pour l'instant.",
    availabilityDetailsRequired: "Choisissez un jour, une heure de début et une heure de fin valides.",
    availabilityDuplicate: "Cette disponibilité existe déjà.",
    availabilityOverlap: "Cette plage chevauche déjà une autre disponibilité active.",
    feedbackTitle: "Votre retour",
    feedbackSession: "Séance concernée",
    sessionRating: "Satisfaction",
    clarityRating: "Clarté du suivi",
    followUpNeeded: "Souhaitez-vous un suivi?",
    feedbackComment: "Commentaire facultatif",
    submitFeedback: "Envoyer le retour",
    feedbackSent: "Merci, votre retour a été enregistré.",
    feedbackDetailsRequired: "Choisissez une séance et donnez deux évaluations.",
    feedbackNotAvailable: "Le retour est disponible après la séance.",
    parentFeedback: "Retours parents",
    testData: "Autres données de test",
    testDataHelp: "Les parents, tuteurs, séances, paiements, retours et demandes marqués test, demo, example, sample, mock, fake, essai ou qa apparaissent ici.",
    noTestData: "Aucune donnée de test à supprimer.",
    deleteTest: "Supprimer",
    testDeleted: "Donnée de test supprimée.",
    deleteAllTest: "Supprimer tous les tests",
    deleteAllTestConfirm: "Supprimer toutes les données de test affichées? Cette action retire aussi les données liées aux comptes de test.",
    testAllDeleted: "Données de test supprimées.",
    testRecordNotFound: "Cette donnée de test n'est plus disponible.",
    priorityTitle: "A traiter maintenant",
    priorityIntro: "Les files sont mises a jour depuis le CRM pour guider la prochaine action de l'equipe.",
    queueCallbacks: "Appels parents",
    queueMatching: "Matching",
    queueConfirmations: "Confirmations",
    queueCalendar: "Calendrier",
    queueNotes: "Bilans tuteurs",
    queuePayments: "Paiements",
    queueMessages: "Messages",
    queueEmpty: "Aucun element en attente.",
    automationTitle: "Automatisations",
    automationReminders: "Rappels",
    automationCalendar: "Calendrier",
    automationDigest: "Point equipe",
    automationPayments: "Paiement",
    automationReminderDetail: "avant seance, bilan et retour parent",
    automationCalendarDetail: "cree apres les deux confirmations",
    automationDigestDetail: "chaque jour",
    paymentModeCheckout: "Checkout Stripe sécurisés",
    paymentModeUnavailable: "Configuration requise",
    empty: "Rien à afficher pour l'instant.",
    loginHelp:
      "Ce portail est destiné aux clients existants. Les accès tuteurs sont créés uniquement par l'équipe.",
    createHelp:
      "Cette demande crée votre fiche de suivi; l'équipe propose d'abord le tuteur et le créneau. Aucun paiement ni engagement n'est confirmé ici.",
    createStepsTitle: "Après votre demande",
    createSteps: [
      "Vous confirmez votre adresse avec un code reçu par email.",
      "L'équipe reçoit la matière, le niveau et le besoin à cadrer.",
      "Le tuteur et le créneau sont proposés avant votre confirmation.",
    ],
    error: "Une erreur est survenue. Réessayez ou contactez Méthode Secondaire.",
  },
  en: {
    seoTitle: "Client portal sign-in | Méthode Secondaire",
    seoDescription:
      "Sign-in reserved for current parents and tutors to follow sessions, payments, notes and next actions.",
    badge: "Méthode Secondaire client portal",
    title: "Access your client portal.",
    subtitle:
      "This space is reserved for current parents and tutors. Sign in with the code received by email to view your sessions, payments and follow-up.",
    firstSessionRequestBadge: "First-session request",
    firstSessionRequestTitle: "Tell us about your student's situation.",
    firstSessionRequestSubtitle:
      "Share the grade, subject and need. The team will then propose a tutor and time; the portal is used for follow-up after your first confirmation.",
    newClientPrompt: "Looking for a tutor for the first time?",
    newClientAction: "Request a first session",
    parent: "Parent",
    tutor: "Tutor",
    operator: "Team",
    loginTab: "Sign in",
    createTab: "My request",
    existingAccessTitle: "I already have access",
    createParentTitle: "First-session request",
    createTutorTitle: "Tutor access request",
    email: "Email address",
    code: "Code received by email",
    sendCode: "Get a code",
    verifyCode: "Sign in",
    parentName: "Parent name",
    phone: "Phone",
    studentLevelSubject: "Grade and subject",
    mainConcern: "Main need",
    preferredFormat: "Preferred format",
    tutorName: "Tutor name",
    tutorSubjects: "Subjects and grades",
    createParentAccount: "Send my request",
    createTutorRequest: "Request access",
    privacyConsent: "I agree that Méthode Secondaire may keep this information to organize sessions, follow-up and payments.",
    codeSent:
      "If access exists for this address, a code has been sent. Please check spam too.",
    sendingCode: "Sending code...",
    signingIn: "Signing in...",
    creatingAccount: "Creating account...",
    loadingDashboard: "Loading your space...",
    loadingDashboardSlow: "Connecting to the CRM. Your data remains secure.",
    serviceTimeout:
      "The service is taking longer than expected. Refresh in a moment; your session and data are still safe.",
    dashboardDisplayError:
      "The dashboard received data, but one section could not be displayed. Your data remains safe.",
    retryDashboard: "Retry dashboard",
    accountCreated:
      "Request received. A code has been sent to your email to confirm access to your follow-up.",
    existingAccountCodeSent:
      "Access already exists for this address. A code has been sent.",
    tutorRequestSent:
      "Request received. Tutor access will be enabled after roster approval.",
    tutorInviteRequired: "Tutor access is created and sent only by the Méthode Secondaire team.",
    tutorInviteTitle: "Tutor access",
    tutorCreateTitle: "Add a tutor",
    tutorCreateIntro: "Create the profile, then the tutor receives a sign-in code by email.",
    tutorExistingTitle: "Existing access",
    tutorInviteStatus: "Access status",
    inviteTutor: "Create and send access",
    tutorInvited: "Tutor access created. A sign-in code was sent.",
    createTutor: "Create tutor and send access",
    tutorCreatedAndInvited: "Tutor created and access sent by email.",
    tutorCreatedInvitePending: "Tutor created. Send the access below when email delivery is available.",
    tutorDetailsRequired: "Add a name, email, subjects, grades, format and a capacity from 1 to 40 students.",
    tutorEmailInUse: "This email address already belongs to a tutor.",
    tutorLevels: "Grades covered",
    tutorWeeklyCapacity: "Weekly capacity (students)",
    tutorLanguage: "Working language",
    tutorZones: "Area or service zone",
    tutorRate: "Hourly rate (CAD/h — $28 base, adjusted by experience and role)",
    tutorRateInvalid: "The hourly rate must be at least CAD $28/hour.",
    tutorNotes: "Internal note (optional)",
    tutorInviteDetailsRequired: "Choose an active tutor with a calendar email address.",
    logout: "Sign out",
    cancel: "Cancel",
    refresh: "Refresh",
    setupPending:
      "The portal is ready on the website, but Apps Script email authorization may still be needed if no code arrives.",
    apiUnavailable:
      "The portal API is not responding here. In local development, restart the site and try again; in production, check the Vercel configuration.",
    accountRequired: "Add at least the name and email to create access.",
    privacyConsentRequired: "Consent is required to create the parent account.",
    emailRequired: "Enter a valid email address.",
    emailNotAuthorized:
      "Email code delivery needs a one-time Google Apps Script authorization. Please retry shortly or contact Méthode Secondaire.",
    emailQuotaReached:
      "Email code delivery is temporarily unavailable. Please retry later or contact Méthode Secondaire.",
    emailSendFailed:
      "The code could not be sent. Please retry shortly or contact Méthode Secondaire.",
    loginFailed: "The code or email address is incorrect. Request a new code and try again.",
    loginCooldown: "Too many incorrect codes were entered. Wait 15 minutes before requesting a new code.",
    codeExpired: "This code has expired. Request a new code.",
    sessionExpired: "Your session is no longer active. Request a new code to sign in again.",
    parentDashboard: "Parent space",
    tutorDashboard: "Tutor space",
    operatorDashboard: "Session management",
    parentJourneyTitle: "Your journey",
    parentJourneyProfile: "Profile received",
    parentJourneyMatching: "Tutor proposed",
    parentJourneyBooking: "Session booked",
    parentJourneyFollowUp: "Follow-up underway",
    parentJourneyCurrent: "In progress",
    parentJourneyDone: "Complete",
    parentJourneyEyebrow: "Your family follow-up",
    parentJourneyNext: "Next step",
    parentJourneyCount: "steps complete",
    parentJourneyCompleteMessage: "Everything is in place. Your portal now keeps the full picture clear.",
    parentActionEyebrow: "Do this now",
    parentActionProfile: "Complete your profile",
    parentActionProfileText: "Add the few useful details that help matching start with the right context.",
    parentActionMatching: "Matching is being prepared",
    parentActionMatchingText: "Your request is safely received. We will suggest the right tutor before booking.",
    parentActionBooking: "Choose a first session",
    parentActionBookingText: "Your tutor is ready: simply choose the time that works for your family.",
    parentActionPayment: "Complete the payment",
    parentActionPaymentText: "A payment needs your attention to keep the session confirmed.",
    parentActionMessage: "Reply to the latest message",
    parentActionMessageText: "A quick reply helps the team and tutor prepare what comes next.",
    parentActionAllSet: "Everything is up to date",
    parentActionAllSetText: "Your family is ready. The next helpful milestone will appear here at the right time.",
    parentActionOpen: "See the next step",
    parentNavLabel: "Parent portal navigation",
    parentNavToday: "Today",
    parentNavSessions: "Sessions",
    parentNavMessages: "Messages",
    parentNavAccount: "Family & account",
    sessionProgressEyebrow: "Session milestones",
    sessionProgressTitle: "Your next session at a glance",
    sessionProgressPrepare: "Prepare the session",
    sessionProgressMeet: "Meet with the tutor",
    sessionProgressRecap: "Read the recap",
    sessionProgressUpcoming: "Upcoming",
    rhythmEyebrow: "Your rhythm",
    rhythmTitle: "Follow-up that stays simple",
    rhythmNoContract: "No subscription or automatic renewal",
    rhythmNoContractText: "The cadence is chosen with you after matching. It organizes the block's sessions without creating a subscription.",
    rhythmSameTutor: "Same tutor, same time",
    rhythmSameTutorText: "Your follow-up keeps its context: less repeating and more continuity.",
    rhythmDeadline: "Planning deadline",
    rhythmDeadlineFallback: `Plan any change at least ${pricing.cancellation.noticeHours} hours before a session.`,
    rhythmDeadlinePassed: `The ${pricing.cancellation.noticeHours}-hour window has passed: the team can still review an adjustment.`,
    rhythmPause: "Pause this rhythm",
    rhythmResume: "Resume this rhythm",
    rhythmPauseHelp: `A pause applies to future sessions that are not yet inside the ${pricing.cancellation.noticeHours}-hour window. No real payment is triggered from this card.`,
    rhythmPauseConfirmed: "The rhythm is paused. Sessions already confirmed still need to be reviewed separately.",
    rhythmResumeConfirmed: "The rhythm is resumed. The team and tutor can see your cadence again.",
    rhythmPauseSetup: "The team first activates this rhythm in your file; you will then be able to pause it here.",
    rhythmManage: "Manage sessions",
    rhythmPriceNote: "Cadence is confirmed after matching; it never renews the block automatically.",
    programEyebrow: "Your block",
    programCredits: "sessions left",
    programOutOf: "of",
    programUsed: "sessions used",
    programAction: "See program sessions",
    programPending: "Program being activated",
    programMidpointPaymentIntro: "Credits remaining: {credits}. Pay the second {amount} installment before booking a sixth session.",
    programMidpointPaymentAction: "Prepare the second payment",
    programMidpointPaymentOpen: "Open secure Stripe payment",
    programMidpointPaymentUnavailable: "The payment was prepared, but its secure Stripe link is not available yet. Try again in a few moments.",
    materialsEyebrow: "Before the session",
    materialsTitle: "Prepare the session",
    materialsDescription: "A photo of homework, the chapter, or an exam helps the tutor focus faster.",
    materialsNoSession: "Once a session is scheduled, you will be able to prepare what your student wants to work on here.",
    materialsCapture: "Take a photo",
    materialsAddFile: "Add photos or a PDF",
    materialsSelected: "On this device",
    materialsReceived: "Documents received",
    materialsRemove: "Remove",
    materialsNote: "What feels most stuck? (optional)",
    materialsNotePlaceholder: "For example: I do not know how to start question 4.",
    materialsFileTypes: "JPG, PNG or WebP photos and PDF files only.",
    materialsFileLimit: "Maximum 2.5 MiB per file.",
    materialsSessionLimit: "Maximum five files per session.",
    materialsFileInvalid: "This file cannot be processed. Choose a valid photo or PDF.",
    materialsProcessingFailed: "The photo could not be prepared. Try again or choose another file.",
    materialsNotAvailable: "Materials can be shared or withdrawn only before an upcoming session.",
    materialsStorageNotConfigured: "Secure material transfer is not configured yet. Contact Méthode Secondaire.",
    materialsStorageFailed: "The material could not be stored. Try again in a few moments.",
    materialsCleanupFailed: "The material could not be shared and its cleanup must be checked by the team.",
    materialsShareFailed: "Tutor access to the material could not be confirmed. The material was not shared.",
    materialsWithdrawFailed: "The material could not be withdrawn. Try again or contact Méthode Secondaire.",
    materialsReadyState: "Ready",
    materialsUploading: "Uploading...",
    materialsShared: "Shared with your tutor",
    materialsFailed: "Failed",
    materialsRetry: "Try again",
    materialsSendToTutor: "Send to tutor",
    materialsWithdraw: "Withdraw",
    materialsWithdrawn: "The material was withdrawn from the tutor's access.",
    materialsRetention: "Shared materials are deleted 30 days after the session ends.",
    materialsOpen: "Open material",
    materialsOpenUnavailable: "Material temporarily unavailable",
    tutorMaterialsEyebrow: "Before the session",
    tutorMaterialsTitle: "Materials shared by parents",
    calendarNoSessions: "No sessions scheduled this week.",
    profileTitle: "Learning profile",
    profileIntro: "Keep the student's information current so each session starts with the right context.",
    profileSaved: "Learning profile updated.",
    profileDetailsRequired: "Add at least your name before saving the profile.",
    profileTimeline: "Important timeline or cadence",
    profileSave: "Save profile",
    welcome: "Hello",
    nextSession: "Next session",
    manageSession: "Manage this session",
    noNextSession: "No confirmed upcoming session.",
    sessions: "Sessions",
    upcomingSessions: "Upcoming",
    followUpSessions: "Needs follow-up",
    pastSessions: "Past",
    cancelledSessions: "Cancelled",
    scheduleSession: "Schedule a session",
    chooseParent: "Choose a parent",
    chooseTutor: "Choose a tutor",
    sessionDate: "Date and time",
    duration: "Duration",
    studentName: "Student name",
    sessionType: "Session type",
    sessionFormat: "Format",
    location: "Location or meeting link",
    recurrence: "Recurrence",
    sessionPrice: "Amount to charge (CAD)",
    sessionPriceDefault: "Default price",
    sessionPriceHelp: "Enter $0 for a free session. From $1, a Stripe Test Checkout is created after confirmation.",
    createSession: "Send proposal",
    sessionCreated: "The session was proposed to both people for confirmation.",
    confirmSession: "Confirm",
    requestChange: "Request a change",
    rescheduleSession: "Change time",
    rescheduleTitle: "Propose a new time",
    rescheduleDate: "New date and time",
    rescheduleDuration: "New duration (minutes)",
    rescheduleSave: "Send new proposal",
    sessionRescheduled: "New time proposed. The parent and tutor now need to confirm.",
    rescheduleNotAvailable: "This session can no longer be rescheduled.",
    cancelSession: "Cancel session",
    cancellationPolicy: `With ${pricing.cancellation.noticeHours} hours' notice, rescheduling is guaranteed. Later requests are reviewed by the team; no credit or payment is removed automatically.`,
    cancellationConfirmed: "Session cancelled. Calendar and unpaid payment were updated.",
    cancellationReview: "Cancellation request sent to the team for review.",
    operatorCancellationConfirm: "Cancel this session? The parent, tutor, calendar and outstanding payment will be updated.",
    operatorCancellationConfirmed: "Session cancelled by the team. Calendar and payment were updated.",
    cancellationNotAvailable: "This session can no longer be cancelled from the portal.",
    sessionConfirmed: "Confirmation saved. Calendar and payment will follow once both people confirm.",
    sessionChangeRequested: "The change request was sent to the team.",
    confirmationWaiting: "Waiting for the other confirmation",
    parentConfirmed: "Parent confirmed",
    tutorConfirmed: "Tutor confirmed",
    paymentReady: "Payment ready",
    sessionAwaitingTutor: "You confirmed — waiting for the tutor to confirm.",
    sessionAwaitingParent: "The tutor confirmed — your confirmation is needed.",
    sessionProposalExpired: "This proposal has expired.",
    sessionProposalExpiredText: "Request a change and the team will propose a new time.",
    sessionRecapTitle: "Session recap",
    planSetupTitle: "Blocks and payments",
    planSetupIntro: "Create a Momentum block or a Progress block. Stripe verification automatically grants the included credits exactly once.",
    planChoose: "Offer",
    planChooseParent: "Parent",
    planChooseStudent: "Student",
    planChooseTutor: "Tutor",
    planCadence: "Cadence after matching",
    planCadenceHelp: "Choose a rhythm only after confirming the tutor and the family's availability.",
    planCadenceOptions: {
      one_time: "Plan as needed",
      weekly: "Every week",
      biweekly: "Every two weeks",
    },
    planWeekday: "Usual day",
    planTime: "Usual time",
    planSessionLink: "Linked follow-up (optional)",
    planSessionLinkNone: "No linked offer",
    planSessionLinkHelp: "Link this session to active follow-up. A credit is reserved automatically for the 10-session block.",
    planDetailsRequired: "Confirm the student-tutor match, then a realistic cadence, day, and time before creating the block.",
    planActivate: "Create block and send payment",
    planEnrollmentSaved: "Block created in the parent file.",
    planPaymentRequestCreated: "Payment request created. Stripe verification will activate the credits automatically, exactly once.",
    planPaymentRequestTitle: "Block payment request",
    planPaymentRequestOpen: "Open Stripe payment",
    planMidpointTitle: "Progress block midpoint payment",
    planMidpointIntro: `The second ${progressionInstallmentPrice.en} payment becomes available once all first five credits are reserved or used.`,
    planMidpointAction: "Create midpoint payment",
    planMidpointNone: "No Progress block has reached the midpoint yet.",
    planPaymentStageNotReady: "All first five credits must be reserved or used before this payment.",
    planPaymentRequestBusy: "The payment request is being created. Please try again in a few seconds.",
    planAlreadyActive: "This family already has this active offer for this student. Open it instead of creating a second program.",
    planEnrollmentBusy: "The offer is being activated. Please try again in a few seconds.",
    planCannotAdjust: "This offer is no longer active, so its credits cannot be changed.",
    planEnrollmentPending: "Offer created pending: confirm payment before adding credits.",
    planNoPlans: "Offers will be available after the CRM sync.",
    planAdjustTitle: "Exceptional manual credit correction",
    planAdjustHelp: "Use only for exceptional corrections. A specific reason is required; normal payments are credited automatically by Stripe.",
    planSelectEnrollment: "Parent program",
    planCreditAmount: "Credits to add or remove",
    planCreditReason: "Reason for adjustment",
    planCreditReasonRequired: "Add a reason before saving this exceptional correction.",
    planCreditSaved: "Credits updated.",
    paymentDemoAction: "Pay in simulation",
    paymentDemoSuccess: "Simulated payment confirmed. No card was charged.",
    paymentDemoNotAvailable: "This session already uses card payment or can no longer be simulated.",
    bookingTitle: "Book a session",
    bookingIntro: "Choose a time. A secure Stripe payment link will be created for your booking.",
    bookingTutorAndSubjects: "Tutor and subjects",
    bookingTutorAssignmentRequired: "Choose the tutor for this session first.",
    bookingTutorAssignmentSummary: "Selected tutor: {tutor} — Assigned subjects: {subjects}",
    bookingPaymentNotice: "Card payment opens only on Stripe’s secure page.",
    bookingCreditIntro: "Choose a time: one program credit will be reserved for this session.",
    bookingNoSlots: "No time is open right now.",
    bookingPrice: "Price for this session",
    bookingProgramCredit: "1 program credit",
    bookingPlanCredit: "1 program credit will be reserved for this session.",
    bookingProgramCreditNotice: "The credit is reserved now and used only after the session is completed.",
    bookingProgramPaymentRequired: "The first five credits are already reserved or used. Go to the block payment under “Family & account” before booking another session.",
    bookingProgramPaymentAction: "Go to block payment",
    matchingPendingTitle: "We are preparing the right match",
    matchingPendingIntro: "Your profile is in. The team will propose a tutor before showing that tutor's available times.",
    matchingPendingCall: "Urgent or complex situation? Call us.",
    chooseSlot: "Choose this time",
    bookingStudentName: "Student name",
    bookingChooseChild: "Student",
    bookingAddChild: "Add a student before booking a time.",
    bookSession: "Book and pay",
    bookWithProgramCredit: "Book with a credit",
    bookingLoading: "Confirming time...",
    bookingCheckoutReady: "Session booked. Your secure Stripe payment is ready.",
    bookingTestCheckoutReady: "Session booked. Your Stripe test Checkout is ready; no real card will be charged.",
    bookingPaymentSetupRequired: "Session booked, but Stripe Checkout is not configured yet. No payment was taken; the team must finish setup.",
    bookingCreditSuccess: "Session booked. One program credit is now reserved.",
    bookingFreeSuccess: "Session booked. It is free: no payment is required.",
    bookingDetailsRequired: "Choose a time and add the student name.",
    childrenTitle: "My students",
    childrenIntro: "Each child keeps their grade, tutor and follow-up. Add every student in the family here.",
    childName: "Student name",
    childLevelSubject: "Grade and subjects",
    childLearningNotes: "Useful context for the tutor",
    childTutor: "Student tutor",
    childTutorAssignments: "Assigned tutors and subjects",
    childTutorAssignmentSubjects: "Assigned subjects",
    childTutorAssignmentAdd: "Add this assignment",
    childTutorAssignmentSave: "Save assignment",
    childTutorAssignmentDeactivate: "Remove this assignment",
    childTutorAssignmentSaved: "Tutor and subject assignment saved.",
    childTutorAssignmentDeactivated: "Assignment removed.",
    chooseStudent: "Choose a student",
    addChild: "Add a student",
    saveChild: "Save student",
    childSaved: "Student profile saved.",
    childDetailsRequired: "Add at least the student name.",
    childNotFound: "This student profile is no longer available.",
    childTutorAssigned: "Tutor assigned to this student.",
    childTutorAssignmentRequired: "Choose a student and an active tutor.",
    studentTutorAssignmentDetailsRequired: "Choose an active tutor and enter at least one subject.",
    studentTutorAssignmentRequired: "Choose the tutor and subjects before selecting a time.",
    studentTutorAssignmentNotAvailable: "This assignment is no longer available. Refresh the portal and choose again.",
    studentTutorAssignmentExists: "This tutor is already assigned to this student. Edit the existing assignment subjects.",
    noChildren: "No students have been added yet.",
    calendarTitle: "Calendar",
    calendarIntro: "Sessions, confirmations and reminders stay visible in one place.",
    calendarToday: "Today",
    calendarInviteSent: "Calendar invitation sent",
    calendarReminderSent: "Reminder sent",
    calendarNotSynced: "Sync pending",
    activityTitle: "Family history",
    activityIntro: "Sessions, summaries, messages, payments and requests in order.",
    noActivity: "Upcoming actions and exchanges will appear here.",
    todayTitle: "Today",
    todayIntro: "Calls, confirmations, reminders and sessions that need action now.",
    todayCalls: "Calls to make",
    todayConfirmations: "Sessions to confirm",
    todaySessions: "Today's sessions",
    todayReminders: "Reminders to send",
    bookingSlotUnavailable: "That time was just taken. Choose another one.",
    parentUpdateSent: "The parent summary was sent.",
    nextSessionProposed: "The next session was proposed automatically.",
    sessionDetailsRequired: "Choose a parent, tutor and future date.",
    sessionParticipantMissing: "The selected parent or tutor is no longer available.",
    sessionTimeConflict: "This tutor already has a session at that time. Choose another time.",
    parentManagement: "Parent management",
    teamCreateParentTitle: "Add a parent",
    createParentIntro: "Add a family from a call or referral. Portal access stays under your control.",
    createParentAccess: "Also create parent portal access",
    createParentConsent: "The parent has consented to opening their record and portal access.",
    createParent: "Create parent",
    parentCreated: "Parent added to the CRM.",
    parentCreatedWithAccess: "Parent added and portal access enabled. They can now request their code by email.",
    callFollowUp: "Call follow-up",
    callFollowUpIntro: "Keep every sales callback visible, then move the parent to matching when they are ready.",
    callParent: "Call parent",
    leadStatus: "Lead status",
    callbackNotes: "Call notes",
    saveCallFollowUp: "Save follow-up",
    callFollowUpSaved: "Call follow-up saved.",
    leadFollowUpStatusRequired: "Choose a valid follow-up status.",
    parentManagementIntro: "Every parent profile is here. You can edit it, assign a tutor or delete it with confirmation.",
    parentIntentLabel: "Starting context",
    parentIntentExam: "Exam preparation",
    parentIntentHomework: "Difficult homework",
    parentIntentOngoing: "Recurring difficulties",
    chooseParentAccount: "Choose a parent account",
    assignedTutor: "Assigned tutor",
    saveParent: "Save parent",
    parentSaved: "Parent account updated.",
    parentDetailsRequired: "Add a name and valid email address.",
    parentNotFound: "This parent account is no longer available.",
    parentEmailInUse: "This email address belongs to another parent.",
    parentAccess: "Portal access",
    activateParent: "Enable access",
    deactivateParent: "Disable access",
    parentAccessUpdated: "Parent access updated.",
    assignTutor: "Assign this tutor",
    tutorAssigned: "Tutor assigned. You can now schedule the session.",
    assignmentDetailsRequired: "Choose a parent and active tutor.",
    deleteParent: "Delete parent",
    confirmationEmail: "Re-enter the parent email to confirm",
    parentDeleteConfirmationRequired: "The confirmation email does not match.",
    parentDeleted: "Parent account and related data deleted.",
    tutorManagement: "Tutor management",
    tutorManagementIntro: "Every tutor, active or not, is gathered here. Deletion also removes their access, availability and linked sessions.",
    tutorDetails: "Tutor details",
    tutorStatus: "Roster status",
    tutorCapacity: "Capacity",
    deleteTutor: "Delete tutor",
    confirmationTutorEmail: "Retype the tutor email to confirm",
    tutorDeleteConfirmationRequired: "The confirmation email does not match.",
    tutorDeleted: "Tutor and related data deleted.",
    tutorNotFound: "This tutor is no longer available.",
    tutorPublicProfileTitle: "Tutor public profile",
    tutorPublicProfileIntro: "Visible only after team approval and the tutor's consent.",
    tutorPublicProfileDisplayName: "Display name",
    tutorPublicProfilePhotoUrl: "HTTPS photo URL (optional)",
    tutorPublicProfilePhotoAltFr: "Photo alt text (FR)",
    tutorPublicProfilePhotoAltEn: "Photo alt text (EN)",
    tutorPublicProfileHeadlineFr: "Short headline (FR)",
    tutorPublicProfileHeadlineEn: "Short headline (EN)",
    tutorPublicProfileBioFr: "Introduction (FR)",
    tutorPublicProfileBioEn: "Introduction (EN)",
    tutorPublicProfileStyleFr: "Teaching style (FR)",
    tutorPublicProfileStyleEn: "Teaching style (EN)",
    tutorPublicProfileVisibility: "Visibility",
    tutorPublicProfileDraft: "Draft",
    tutorPublicProfilePublished: "Published",
    tutorPublicProfileHidden: "Hidden",
    tutorPublicProfileConsent: "The tutor has consented to publishing this profile and photo.",
    tutorPublicProfilePublicationRequired: "To publish, add the required French and English content and confirm consent.",
    tutorPublicProfileSave: "Save public profile",
    tutorPublicProfileSaved: "Public profile saved.",
    messagesTitle: "Session messages",
    messageSession: "Session",
    messagePlaceholder: "Write a message",
    sendMessage: "Send message",
    messageSent: "Message sent. The recipient was also notified by email.",
    messageSentPortal: "Message sent in the portal.",
    responseSla: "A reply is expected within 24 hours. The team is alerted if that deadline is missed.",
    messageRequired: "Write a message before sending it.",
    messageNotAllowed: "Messages are limited to the parent and tutor assigned to this session.",
    notes: "Summaries",
    payments: "Payments",
    amount: "Amount",
    freeSession: "Free",
    pay: "Pay",
    paid: "Paid",
    paymentDueOneHour: "Payment due within one hour",
    paymentDueUntil: "Pay by",
    paymentLinkPreparing: "Your secure Stripe link is being prepared. Refresh in a moment; no payment has been charged.",
    paymentLinkExpired: "This payment link has expired.",
    requestNewPaymentLink: "Request a new payment link",
    paymentReissueSuccess: "A new secure payment link is ready for one hour.",
    bookingReleased: "This booking was released. Choose a new time before paying.",
    meetPreparing: "Google Meet link is being prepared",
    joinGoogleMeet: "Join Google Meet",
    requestTitle: "Ask for follow-up",
    requestHistory: "Request updates",
    requestQueue: "Requests to handle",
    requestStatus: "Status",
    requestSave: "Update",
    requestUpdated: "Request updated.",
    requestStatusRequired: "Choose a valid status.",
    requestNotFound: "This request is no longer available.",
    parentNoteTitle: "Add a note",
    parentNoteSession: "Session",
    parentNoteMessage: "Information to share with the team or tutor",
    parentNoteSent: "Note added to the session follow-up.",
    sessionPrepTitle: "Prepare the next session",
    sessionPrepIntro: "Share the priority, homework or a context change directly with the tutor.",
    sessionPrepMessage: "Priority, homework, assessment or context to know before the session",
    sessionPrepSent: "Preparation sent to the tutor in the session space.",
    requestSubject: "Subject",
    requestMessage: "Message",
    sendRequest: "Send request",
    requestSent: "Request sent. It now appears in the CRM.",
    noteTitle: "Post-session note",
    chooseSession: "Choose a session",
    attendance: "Attendance",
    focusWorked: "What was covered",
    wins: "What improved",
    stuckPoints: "What is still blocked",
    homeworkNext: "Work before next session",
    parentSummary: "Parent summary",
    studentConfidence: "Student confidence",
    nextGoal: "Next goal",
    riskLevel: "Risk",
    recommendation: "Recommendation",
    submitNote: "Submit note",
    noteSent: "Note received. The parent summary is ready for review.",
    noteNotReady: "The session note can be submitted after the session ends.",
    availabilityTitle: "My availability",
    availabilityIntro: "Open windows here become bookable by parents in the portal.",
    availabilityAdd: "Add availability",
    availabilitySave: "Save availability",
    availabilityEdit: "Edit",
    availabilityDay: "Day",
    availabilityStart: "Start",
    availabilityEnd: "End",
    availabilityStatus: "Status",
    availabilitySaved: "Availability updated.",
    availabilityPause: "Pause",
    availabilityOpen: "Open",
    availabilityEmpty: "No availability is published yet.",
    availabilityDetailsRequired: "Choose a valid day, start time and end time.",
    availabilityDuplicate: "This availability already exists.",
    availabilityOverlap: "This window overlaps another active availability.",
    feedbackTitle: "Your feedback",
    feedbackSession: "Session",
    sessionRating: "Satisfaction",
    clarityRating: "Clarity of follow-up",
    followUpNeeded: "Would you like follow-up?",
    feedbackComment: "Optional comment",
    submitFeedback: "Send feedback",
    feedbackSent: "Thank you, your feedback was recorded.",
    feedbackDetailsRequired: "Choose a session and provide both ratings.",
    feedbackNotAvailable: "Feedback is available after the session.",
    parentFeedback: "Parent feedback",
    testData: "Other test data",
    testDataHelp: "Parents, tutors, sessions, payments, feedback and requests marked test, demo, example, sample, mock, fake, essai or qa appear here.",
    noTestData: "No test data to delete.",
    deleteTest: "Delete",
    testDeleted: "Test data deleted.",
    deleteAllTest: "Delete all tests",
    deleteAllTestConfirm: "Delete every displayed test record? This also removes data linked to test accounts.",
    testAllDeleted: "Test data deleted.",
    testRecordNotFound: "This test record is no longer available.",
    priorityTitle: "Handle now",
    priorityIntro: "These queues are updated from the CRM to guide the team's next action.",
    queueCallbacks: "Parent calls",
    queueMatching: "Matching",
    queueConfirmations: "Confirmations",
    queueCalendar: "Calendar",
    queueNotes: "Tutor notes",
    queuePayments: "Payments",
    queueMessages: "Messages",
    queueEmpty: "Nothing waiting.",
    automationTitle: "Automations",
    automationReminders: "Reminders",
    automationCalendar: "Calendar",
    automationDigest: "Team digest",
    automationPayments: "Payments",
    automationReminderDetail: "before sessions, notes and parent feedback",
    automationCalendarDetail: "created after both confirmations",
    automationDigestDetail: "every day",
    paymentModeCheckout: "Secure Stripe Checkout",
    paymentModeUnavailable: "Setup required",
    empty: "Nothing to show yet.",
    loginHelp:
      "This portal is for current clients. Tutor access is created only by the team.",
    createHelp:
      "This request creates your follow-up profile; the team first proposes a tutor and time. No payment or commitment is confirmed here.",
    createStepsTitle: "After your request",
    createSteps: [
      "Confirm your email address with the code you receive.",
      "The team receives the subject, grade and need to frame.",
      "The tutor and time are proposed before you confirm.",
    ],
    error: "Something went wrong. Please try again or contact Méthode Secondaire.",
  },
}
export function getPortalCopy(locale = "fr") {
  return portalCopyByLocale[locale] || portalCopyByLocale.fr
}
